version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5534:5000"
    volumes:
      - ./instance:/app/instance # SQLite data safe rakhne ke liye
      - ./static/uploads:/app/static/uploads # NAYA: Uploaded images hamesha safe rahenge
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8834:80" 
    depends_on:
      - backend
    restart: always